### ISSUE TITLE
Interactive plotting of graphs

### ISSUE THREAD

**Issue by dennlinger** [Jan-Kerschbaum/Parec#1]
I mentioned an incorrect library yesterday (d3.js), which is not so suitable for plotting graphs.
Instead, I was using [vis.js](https://visjs.org/), which I highly recommend for simple JS-based graph visualizations.

**Comment by dennlinger** [comment]
There seems also to be a related python-based implementation called [`pyvis`](https://pyvis.readthedocs.io/en/latest/), which you might be able to serve directly via fastAPI.

**Comment by Jan-Kerschbaum** [comment]
Current implementation of the frontend on the ui_migration branch, awaiting revision before merge, now employs a vis graph. Thanks for the suggestion once again.

Won't close the issue quite yet though, since (re-)generation of the graph is not yet implemented.

**Comment by Jan-Kerschbaum** [comment]
Status update: branch graph_rebuilding_dev implements automatic building of graph from list of edges provided by backend.

Still awaiting code review for merge and possible visual changes.

**Comment by Jan-Kerschbaum** [comment]
Merged to main, closing issue.
