### ISSUE TITLE
Svelte port forwarding

### ISSUE THREAD

**Issue by dennlinger** [Jan-Kerschbaum/Parec#2]
You mentioned another issue regarding the port forwarding of the Svelte container. Feel free to upload a Dockerfile or other definitions in the repository to help me reproduce (and hopefully resolve) the issue.

**Comment by DiliAy** [comment]
The issue is resolved.
I accidentally used the framework sveltekit in the beginning, even though we use plain svelet in the project. After switching it worked as intended.
