### ISSUE TITLE
Meeting Questions

### ISSUE THREAD

**Issue by friebolin** [Jan-Kerschbaum/Parec#6]
Hi,

in our meeting tomorrow we'd like to discuss the following points:

1. General Code review
2. Size of our data set
3. Loading data to ES (currently, we are loading/indexing the data each time to ES, then retrieving it)

Thank you and see you tomorrow,
Sandra

**Comment by dennlinger** [comment]
* Can you clarify on the problems with the size of your data set (point 2)?
* For point 3, I'm not sure what "each time" means in this context. Why is data updated so frequently, and can this be reduced to a singular pass over the indexing?

**Comment by dennlinger** [comment]
As for the code review, please let me know in which branches I should look. On `main`, it seems no functionality for data ingestion is included (yet?). I'm not going to review each single branch, so it would be great if you can help me out here.  

As for the current state on the main branch, here are some minor immediate comments:

* In `parec-backend/app/main.py`: Functions like `test_function()` should probably not be part of the actual `Data` class, and rather be realized via a separate test suite (e.g., a separate file `tests.py`, based on `unittest` or `pytest`. For `fastapi`, there are also included some specific [test environments](https://fastapi.tiangolo.com/tutorial/testing/).
* For the frontend, you could think about separating out styling comments in `App.svelte` to `app.css`.

**Comment by friebolin** [comment]
Hi, the branch we are mainly working on is called backend_basic_dev - sorry for the confusion!

**Comment by dennlinger** [comment]
Is there any reason why you are working on this branch? I highly recommend to do regular PR's with main, simply to make it easier to do a final merge.
